### ISSUE TITLE
Program type already present: ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by ArthurAttout** [Sh1d0w/multi_image_picker#151]
TBH, this is an issue I have all the time, and I have absolutely no idea how to debug them. 

Creating a simple flutter app project with only two dependencies will throw an exception 

pubspec : 

```
name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  multi_image_picker: ^4.3.1
  image_picker: ^0.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

Exception thrown : 

```

D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\wrkfldr\flutter_app\build\app\intermediates\transforms\dexBuilder\debug\2.jar, D:\wrkfldr\flutter_app\build\app\intermediates\transforms\dexBuilder\debug\3.jar, D:\wrkfldr\flutter_app\build\app\intermediates\transforms\dexBuilder\debug\6.jar, D:\wrkfldr\flutter_app\build\app\intermediates\transforms\dexBuilder\debug\7.jar, D:\wrkfldr\flutter_app\build\app\intermediates\transforms\dexBuilder\debug\111.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

```

Is there any way I could use both these dependencies in the same project ?
