### ISSUE TITLE
Flutter 1.12 version crash on Android

### ISSUE THREAD

**Issue by nafis042** [Sh1d0w/multi_image_picker#374]
**Bug Report**

`multi_image_picker` version: 4.6.1

Is it happening on Android: Yes

Is it happening on iOS: No

```
 [✓] Flutter (Channel master, v1.13.10-pre.64, on Mac OS X 10.15.3 19D62e, locale
    en-BD)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!
```

**Describe the bug**

before upgrading flutter version 1.12 everything was fine but after the upgrade and following the new migration rule for [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)(beacuse I have a custom plugin for my project) I am getting the following error message:

```
E/MethodChannel#multi_image_picker(15336): Failed to handle method call
E/MethodChannel#multi_image_picker(15336): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/MethodChannel#multi_image_picker(15336): 	at com.sangcomz.fishbun.FishBun$Companion.with(Unknown Source:2)
E/MethodChannel#multi_image_picker(15336): 	at com.sangcomz.fishbun.FishBun.with(Unknown Source:2)
E/MethodChannel#multi_image_picker(15336): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:526)
E/MethodChannel#multi_image_picker(15336): 	at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:251)
E/MethodChannel#multi_image_picker(15336): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#multi_image_picker(15336): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#multi_image_picker(15336): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#multi_image_picker(15336): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#multi_image_picker(15336): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#multi_image_picker(15336): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#multi_image_picker(15336): 	at android.app.ActivityThread.main(ActivityThread.java:6986)
E/MethodChannel#multi_image_picker(15336): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#multi_image_picker(15336): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#multi_image_picker(15336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by AlexVincent525** [comment]
Hi, I met this too.
After permission was granted at first, this error log appeared.
If you try to run `loadAssets` again, it'll tell you `Image picker is already active`.

## Environment

**Flutter Version: ** 1.12.13+hotfix.5
**Platform: ** [✓] Android / [ ] iOS
**Package Version: ** 4.6.1

Project created with android embedding v2 enabled.

## Example code
```
final assets = <Asset>[];

Future<Null> loadAssets() async {
  List<Asset> resultList = List<Asset>();
  final permissions = await PermissionHandler().requestPermissions([
    PermissionGroup.camera,
    PermissionGroup.storage,
  ]);
  if (permissions[PermissionGroup.camera] == PermissionStatus.granted &&
      permissions[PermissionGroup.storage] == PermissionStatus.granted) {
    try {
      final results = await MultiImagePicker.pickImages(
        maxImages: 9,
        selectedAssets: assets,
        cupertinoOptions: CupertinoOptions(takePhotoIcon: "chat"),
        materialOptions: MaterialOptions(
          actionBarColor: "#abcdef",
          actionBarTitle: "Example App",
          allViewTitle: "All Photos",
          useDetailsView: false,
          selectCircleStrokeColor: "#000000",
        ),
      ).catchError((e) {
        debugPrint(e.toString());
      });
      if (results != null) resultList = results;
    } on Exception catch (e) {
      debugPrint('Open multi image picker failed: $e');
    }
  } else {
    return;
  }
}
```

**Comment by AlexVincent525** [comment]
You can run the project from https://github.com/AlexVincent525/flutter_test_app , which includes a simple demo for this issue.

**Comment by joker-fu** [comment]
multi_image_picker version: 4.6.1

Is it happening on Android: Yes

Is it happening on iOS: No


    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
        at com.sangcomz.fishbun.FishBun$Companion.with(Unknown Source:2)
        at com.sangcomz.fishbun.FishBun.with(Unknown Source:2)
        at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:493)
        at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:227)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Yask0** [comment]
Any updates on this? Running into same issue.

**Comment by Sh1d0w** [comment]
Sorry for the delay guys, I've been busy with work stuff.

@nafis042 Thanks for reporting this. I've upgraded the example repo of this project with the steps provided and all it seems to be working just fine.

The error you are getting (thanks @AlexVincent525 for the example repo) is because you did not upgrade correctly the project, more specifically you are missing [this line](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/android/app/src/main/kotlin/com/vitanov/example/MainActivity.kt#L10) in the [example repo activity](https://github.com/AlexVincent525/flutter_test_app/blob/master/android/app/src/main/java/com/example/testapp/MainActivity.java) . Once you put it there the error will no longer appear.

**Comment by AlexVincent525** [comment]
> more specifically you are missing [this line](https://github.com/Sh1d0w/multi_image_picker/blob/master/example/android/app/src/main/kotlin/com/vitanov/example/MainActivity.kt#L10)

In my project I've already placed this line. [MainActivity.java](https://github.com/openjmu/OpenJMU/blob/master/android/app/src/main/java/cn/edu/jmu/openjmu/MainActivity.java#L15), it got the error from my comment https://github.com/Sh1d0w/multi_image_picker/issues/374#issuecomment-578464282 , see **Another case** section.

**Comment by Sh1d0w** [comment]
@AlexVincent525 Regarding that, are you using the latest version of the library? It seems to me like you are not, since the error you are getting occurs in `onRequestPermissionsResult`, but this method was removed [in the latest version](https://github.com/Sh1d0w/multi_image_picker/blob/master/CHANGELOG.md#2020-01-04)

**Comment by AlexVincent525** [comment]
> @AlexVincent525 Regarding that, are you using the latest version of the library?

Sure I did, you can see from my comment before that I pointed out my version for this plugin. And this issue seems disappeared now. Maybe it just ran from the cache or something. BTW thanks for fixing this 👍

**Comment by Yask0** [comment]
This is my mainActivity.java MainActivity, 
```
public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```

The app crashes right away when configureFlutterEngine is added with 

> [  +32 ms] W/FlutterEngine(21834): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1cf67e0) but could not find and invoke the GeneratedPluginRegistrant.

if I remove configureFlutterEngine, app works but I'm back at the issue with the error followed by  "image picker is already open" and with the same output as @joker-fu see below,

```[+5671 ms] E/MethodChannel#multi_image_picker(22720): Failed to handle method call
[   +1 ms] E/MethodChannel#multi_image_picker(22720): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at com.sangcomz.fishbun.FishBun$Companion.with(Unknown Source:2)
[  +38 ms] E/MethodChannel#multi_image_picker(22720):   at com.sangcomz.fishbun.FishBun.with(Unknown Source:2)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at com.vitanov.multiimagepicker.MultiImagePickerPlugin.presentPicker(MultiImagePickerPlugin.java:493)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onMethodCall(MultiImagePickerPlugin.java:227)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[  +21 ms] E/MethodChannel#multi_image_picker(22720):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at android.os.MessageQueue.nativePollOnce(Native Method)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at android.os.MessageQueue.next(MessageQueue.java:325)
[  +21 ms] E/MethodChannel#multi_image_picker(22720):   at android.os.Looper.loop(Looper.java:142)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at android.app.ActivityThread.main(ActivityThread.java:6494)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/MethodChannel#multi_image_picker(22720):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[  +68 ms] E/MethodChannel#multi_image_picker(22720):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)```

**Comment by Sh1d0w** [comment]
@Yask0 Do you get this error while running the app in the example folder of this repo?

If no, then please provide an example repository which I can run and reproduce the error.

**Comment by Yask0** [comment]
I ran the example and that worked, but with my app currently I'm still running into same issue above. I do not have an example folder for you to reproduce the issue I'm seeing. I had multi image working before upgrading flutter and changing to this new flutter embedding, I made all the changes  above and looked your example over, still not sure what the difference is. 

manifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.myapp.android">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application android:label="MyApp" android:icon="@mipmap/ic_launcher">

        <uses-library android:name="org.apache.http.legacy" android:required="false" />
        <meta-data android:name="com.google.android.geo.API_KEY" android:value="@string/google_maps_api_key"/>
        <!-- Set custom default icon. This is used when no icon is set for incoming notification messages. -->
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_ic_notification" />
        <!-- Set color used with incoming notification messages. This is used when no color is set for the incoming notification message.  -->
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" />
        <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <!-- <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" /> -->
            <!-- Set color used with incoming notification messages. This is used when no color is set for the incoming notification message.  -->


            <!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
             See README(https://goo.gl/l4GJaQ) for more. -->
            <!-- <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_ic_notification" /> -->
            <!-- Set color used with incoming notification messages. This is used when no color is set for the incoming
                notification message. See README(https://goo.gl/6BKBk7) for more. -->
            <!-- <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" /> -->
            <!-- <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" /> -->
            <!-- Specify that the launch screen should continue being displayed -->
            <!-- until Flutter renders its first frame. -->
            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <!-- BEGIN: Firebase Cloud Messaging -->
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <!-- END: Firebase Cloud Messaging -->
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data android:name="flutterEmbedding" android:value="2" />
    </application>
</manifest>
```
MainActivity
```
package com.myapp.android;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```
\app
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.myapp.android"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        //codemagic auto versioning, change main version for major builds
        if (System.getenv("CI")) {
            def buildNumber = System.getenv("BUILD_NUMBER")
            versionName = "1.0." + buildNumber 
            versionCode = Integer.valueOf(buildNumber)
        }else{
            versionCode 1
            versionName "1.0"
        }
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
       debug {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
           minifyEnabled true
           useProguard true
       }
       debug{
           signingConfig signingConfigs.debug
           minifyEnabled false
           useProguard false
       }
   }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'androidx.annotation:annotation:1.1.0-rc01'
    implementation 'androidx.test:runner:1.2.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.test:rules:1.2.0'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'

    // Add the Firebase SDK for Crashlytics.
    implementation 'com.google.firebase:firebase-crashlytics:17.0.0-beta01'
    
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```
\android
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta02'
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
pub
```
name: MyApp
description: 

version: 1.0.2+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase
  firebase_core: ^0.4.1+5
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  firebase_messaging: ^5.1.8
  cloud_functions: ^0.4.1+4
  firebase_analytics: ^5.0.6
  firebase_storage: ^3.0.8
  flutter_crashlytics: ^1.0.0
  #google
  google_sign_in: ^4.0.14
  google_maps_flutter: ^0.5.21+15
  flutter_google_places: ^0.2.3
  stripe_payment: ^0.1.1
  #utils
  flutter_screenutil: ^1.0.2
  cupertino_icons: ^0.1.0
  url_launcher: ^5.4.2
  flutter_linkify: ^2.1.0
  location: ^2.3.5
  http: ^0.12.0
  json_serializable: ^2.2.1
  shared_preferences: ^0.5.6+2
  flutter_auth_buttons: ^0.3.1
  flutter_form_builder: '3.6.0'
  flutter_typeahead: ^1.7.0
  #camera/images
  dots_indicator: ^1.0.0
  extended_image: ^0.6.9
  #image_picker: ^0.6.3+1
  multi_image_picker: ^4.6.1
  image_picker: ^0.6.3+1
  #notifications
  flushbar: ^1.9.1
  #flutter_alert: ^0.4.0
  #chat
  dash_chat: ^1.0.15
  #state_management
  provider: ^4.0.2
  #animation
  flare_splash_screen: ^3.0.0
  simple_animations: ^1.3.4
  mask_text_input_formatter: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  image: ^2.0.7
  flutter_launcher_icons: ^0.7.2
  screenshots:
  intl_translation: ^0.17.2
  flutter_driver:
    sdk: flutter

flutter_icons:
  image_path_android: 'assets/icon/logo_image.png'
  image_path_ios: 'assets/icon/logo_image.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/icon/logo_back.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/icon/logo_fore.png' # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  fonts:
    - family: MyApp
      fonts:
        - asset: assets/fonts/MyApp.ttf
    - family: MyAppIcons
      fonts:
        - asset: assets/fonts/MyAppIcons.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - splash.flr
    - logout.flr
    - headerlogo.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

```
